name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        LISP:
          - sbcl-bin
          - ccl-bin
    
    steps:
      - name: Check out IMMUTABLE repository
        uses: actions/checkout@v3
      - name: Grant all perms to make cache restoring possible
        run: |
          sudo mkdir -p /usr/local/etc/roswell
          sudo chown "${USER}" /usr/local/etc/roswell
          # Here the ros binary will be restored:
          sudo chown "${USER}" /usr/local/bin
      - name: Get current month for cache key
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache Roswell Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-roswell
        with:
          path: |
            /usr/local/bin/ros
            ~/.cache/common-lisp/
            ~/.roswell
            /usr/local/etc/roswell
            .qlot
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('qlfile.lock') }}"
      - name: Restore path to cached files
        run: |
          echo $HOME/.roswell/bin >> $GITHUB_PATH
          echo .qlot/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'
      - name: Setup Roswell if not cached
        uses: 40ants/setup-lisp@v2
        with:
          asdf-system: immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run tests
        uses: 40ants/run-tests@v2
        with:
          asdf-system: immutable
        
