name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        LISP:
          - sbcl-bin
          - ccl-bin
    
    steps:
      - uses: actions/checkout@v3
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: immutable
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: immutable
